version: "3.7"
services:
  opensips:
    image: registry.gitlab.com/aec-cti/aec.cti.urasipxml/opensips:prod01
    logging:
      driver: "json-file"
      options:
         max-file: 1
         max-size: 10m
    hostname: opensips
    volumes:
      - "/root/opensips/config/:/usr/local/etc/opensips/"
    networks:
      - outside
    deploy:
      mode: global

  outside:
    external:
      name: "host"
